name: "Pull Request Labeler"
on:
- pull_request

jobs:
  triage:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/labeler@v2
      if: github.repository == 'unoplatform/uno' 
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
